prerelease: true
include-pre-releases: true

name-template: 'v$RESOLVED_VERSION-experimental'
tag-template: 'exp-v$RESOLVED_VERSION'
tag-prefix: 'exp-'
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Other'
    labels:
      - 'documentation'
      - 'other'

exclude-labels:
  - 'ignore changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch

autolabeler:
  - label: 'enhancement'
    title:
      - '/^feat/i'
  - label: 'bug'
    title:
      - '/^fix/i'
  - label: 'other'
    title:
      - '/^ci/i'
      - '/^chore/i'
      - '/^refactor/i'
  - label: 'documentation'
    title:
      - '/^docs/i'

template: |
  ## Changes

  $CHANGES
