prerelease: true
prerelease-identifier: 'exp'

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Other'
    labels:
      - 'documentation'
      - 'other'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch

autolabeler:
  - label: 'enhancement'
    title:
      - '/^feat/i'
  - label: 'bug'
    title:
      - '/^fix/i'
  - label: 'other'
    title:
      - '/^ci/i'
      - '/^chore/i'
      - '/^refactor/i'
  - label: 'documentation'
    title:
      - '/^docs/i'

template: |
  ## Changes

  $CHANGES
